### ISSUE TITLE
Serial not scratching, LJ-Inventory

### ISSUE THREAD

**Issue by z-Lunar** [KevinGirardx/kevin-weaponscratch#2]
As title suggests, followed instructions..weapons serial number is not scratching.

![image](https://user-images.githubusercontent.com/46366594/209292904-8f53f64c-7765-4329-bf03-d592874814fd.png)
![image](https://user-images.githubusercontent.com/46366594/209292947-7f84442a-922d-4f61-a820-3bcdecb44516.png)
![image](https://user-images.githubusercontent.com/46366594/209292983-8c6d876b-3ecc-47ab-815e-b8a68f4af014.png)
![image](https://user-images.githubusercontent.com/46366594/209293044-86ba1b54-94bf-44a7-8353-18bd594af6be.png)

**Comment by KevinGirardx** [comment]
i had a typo, look at the readme now and readd the js snippet to the inventory

**Comment by z-Lunar** [comment]
> i had a typo, look at the readme now and readd the js snippet to the inventory

with this new code, every weapon I have is now considered "Serial Scratched" lol..
