### ISSUE TITLE
i have a error when i use the bench 

### ISSUE THREAD

**Issue by cummins24v2** [KevinGirardx/kevin-weaponscratch#3]
![image](https://user-images.githubusercontent.com/97122395/209499501-5cb97eda-295e-4c9e-b9bd-50789ee531dc.png)

**Comment by KevinGirardx** [comment]
dependencies oxlib

**Comment by MasterManwah** [comment]
Was this recently resolved? I'm having the same issue and we have ox_lib running in our server as other scripts have it as a dependency.

**Comment by KevinGirardx** [comment]
fixed forgot to add the library in the fxmanifest, this should now be resolved
